export const EXERCISES = [
  // CHEST
  { id:'bench_press_bb', name:'Bench Press', category:'Chest', equipment:'Barbell', muscle:'Pectoralis Major', secondary:['Triceps','Front Deltoid'], instructions:'Lie flat on bench. Grip bar slightly wider than shoulder width. Lower bar to chest, press up explosively. Keep shoulder blades retracted.', tips:'Keep feet flat on floor. Drive through your heels for stability.', sets:3, reps:8, emoji:'🏋️' },
  { id:'incline_bench_db', name:'Incline Dumbbell Press', category:'Chest', equipment:'Dumbbell', muscle:'Upper Pectoralis', secondary:['Triceps','Front Deltoid'], instructions:'Set bench to 30-45 degrees. Press dumbbells up and slightly together at top. Control the descent.', tips:'Keep elbows at 45 degrees to protect shoulders.', sets:3, reps:10, emoji:'🏋️' },
  { id:'cable_fly', name:'Cable Crossover', category:'Chest', equipment:'Cable', muscle:'Pectoralis Major', secondary:['Front Deltoid'], instructions:'Stand in center of cable machine. Pull handles down and across body in arc motion. Squeeze chest at bottom.', tips:'Slight forward lean. Keep slight bend in elbows throughout.', sets:3, reps:12, emoji:'🏋️' },
  { id:'push_up', name:'Push Up', category:'Chest', equipment:'Bodyweight', muscle:'Pectoralis Major', secondary:['Triceps','Core'], instructions:'Start in plank position. Lower chest to floor keeping body straight. Press back up.', tips:'Keep core tight. Elbows at 45 degrees.', sets:3, reps:15, emoji:'💪' },
  { id:'dips_chest', name:'Chest Dips', category:'Chest', equipment:'Bodyweight', muscle:'Lower Pectoralis', secondary:['Triceps'], instructions:'Lean forward slightly on parallel bars. Dip down until upper arms parallel to floor. Press back up.', tips:'Forward lean emphasizes chest. Upright targets triceps.', sets:3, reps:10, emoji:'💪' },

  // BACK
  { id:'deadlift', name:'Deadlift', category:'Back', equipment:'Barbell', muscle:'Erector Spinae', secondary:['Hamstrings','Glutes','Traps'], instructions:'Stand with bar over mid-foot. Hip-hinge down, grip bar. Drive through floor, extend hips and knees simultaneously. Lower with control.', tips:'Neutral spine throughout. Bar stays close to body.', sets:3, reps:5, emoji:'🏋️' },
  { id:'pullup', name:'Pull Up', category:'Back', equipment:'Bodyweight', muscle:'Latissimus Dorsi', secondary:['Biceps','Rear Deltoid'], instructions:'Hang with overhand grip. Pull chest to bar leading with elbows. Lower with control.', tips:'Engage lats by pulling shoulders down before pulling up.', sets:3, reps:8, emoji:'💪' },
  { id:'bent_row_bb', name:'Bent Over Row', category:'Back', equipment:'Barbell', muscle:'Latissimus Dorsi', secondary:['Rhomboids','Biceps','Rear Deltoid'], instructions:'Hinge at hips to 45 degrees. Row bar to lower chest/upper abdomen. Keep elbows close to body.', tips:'Retract shoulder blades at top. Control the descent.', sets:3, reps:8, emoji:'🏋️' },
  { id:'lat_pulldown', name:'Lat Pulldown', category:'Back', equipment:'Machine', muscle:'Latissimus Dorsi', secondary:['Biceps'], instructions:'Grip bar wider than shoulder width. Pull to upper chest. Lean back slightly. Return with control.', tips:'Lead with elbows. Squeeze lats at bottom of movement.', sets:3, reps:10, emoji:'🏋️' },
  { id:'cable_row', name:'Seated Cable Row', category:'Back', equipment:'Cable', muscle:'Middle Trapezius', secondary:['Latissimus Dorsi','Biceps'], instructions:'Sit upright. Pull handle to abdomen. Squeeze shoulder blades together. Return with control.', tips:'Dont round back on the stretch. Keep torso upright.', sets:3, reps:12, emoji:'🏋️' },

  // SHOULDERS
  { id:'ohp_bb', name:'Overhead Press', category:'Shoulders', equipment:'Barbell', muscle:'Anterior Deltoid', secondary:['Lateral Deltoid','Triceps','Traps'], instructions:'Stand or sit. Press bar overhead to full extension. Lower to chin level. Keep core braced.', tips:'Do not arch back excessively. Bar path should be straight.', sets:3, reps:8, emoji:'🏋️' },
  { id:'lateral_raise', name:'Lateral Raise', category:'Shoulders', equipment:'Dumbbell', muscle:'Lateral Deltoid', secondary:[], instructions:'Stand with dumbbells at sides. Raise arms to shoulder height in arc motion. Lower with control.', tips:'Slight forward lean. Lead with elbows, not wrists. Do not swing.', sets:3, reps:15, emoji:'🏋️' },
  { id:'face_pull', name:'Face Pull', category:'Shoulders', equipment:'Cable', muscle:'Rear Deltoid', secondary:['External Rotators','Rhomboids'], instructions:'Set cable at face height. Pull to forehead with elbows high and wide. External rotate at end.', tips:'Great for shoulder health. Use lighter weight with full ROM.', sets:3, reps:15, emoji:'🏋️' },
  { id:'front_raise', name:'Front Raise', category:'Shoulders', equipment:'Dumbbell', muscle:'Anterior Deltoid', secondary:[], instructions:'Hold dumbbells in front of thighs. Raise to shoulder height. Lower with control.', tips:'Avoid swinging. Keep slight bend in elbow.', sets:3, reps:12, emoji:'🏋️' },

  // ARMS - BICEPS
  { id:'barbell_curl', name:'Barbell Curl', category:'Arms', equipment:'Barbell', muscle:'Biceps Brachii', secondary:['Brachialis'], instructions:'Stand with barbell. Curl up keeping elbows fixed at sides. Squeeze at top. Lower with control.', tips:'Do not swing body. Supinate wrist at top for peak contraction.', sets:3, reps:10, emoji:'💪' },
  { id:'hammer_curl', name:'Hammer Curl', category:'Arms', equipment:'Dumbbell', muscle:'Brachialis', secondary:['Biceps Brachii'], instructions:'Hold dumbbells with neutral grip (palms facing each other). Curl up alternately or together. Keep elbows fixed.', tips:'Great for overall arm thickness. Full extension at bottom.', sets:3, reps:12, emoji:'💪' },
  { id:'incline_curl', name:'Incline Dumbbell Curl', category:'Arms', equipment:'Dumbbell', muscle:'Biceps Brachii Long Head', secondary:[], instructions:'Sit on inclined bench. Let arms hang. Curl up, supinating wrist. Great for stretch at bottom.', tips:'The stretch at bottom creates excellent bicep stimulus.', sets:3, reps:10, emoji:'💪' },
  { id:'preacher_curl', name:'Preacher Curl', category:'Arms', equipment:'Barbell', muscle:'Biceps Brachii Short Head', secondary:[], instructions:'Rest arms on preacher bench pad. Curl up to full contraction. Lower slowly for full stretch.', tips:'Prevents cheating. Focus on the squeeze at the top.', sets:3, reps:10, emoji:'💪' },

  // ARMS - TRICEPS
  { id:'skull_crusher', name:'Skull Crusher', category:'Arms', equipment:'Barbell', muscle:'Triceps Long Head', secondary:['Triceps Lateral Head'], instructions:'Lie on bench. Hold bar above chest. Lower toward forehead by bending elbows. Extend back up.', tips:'Keep upper arms perpendicular to floor throughout.', sets:3, reps:10, emoji:'🏋️' },
  { id:'tricep_pushdown', name:'Tricep Pushdown', category:'Arms', equipment:'Cable', muscle:'Triceps', secondary:[], instructions:'Face cable machine. Push bar down to full extension. Keep elbows tucked at sides. Control return.', tips:'Do not let elbows flare out. Full extension at bottom.', sets:3, reps:12, emoji:'🏋️' },
  { id:'overhead_tricep', name:'Overhead Tricep Extension', category:'Arms', equipment:'Dumbbell', muscle:'Triceps Long Head', secondary:[], instructions:'Hold dumbbell overhead with both hands. Lower behind head by bending elbows. Extend back up.', tips:'Great for long head stretch. Keep elbows pointing forward.', sets:3, reps:12, emoji:'🏋️' },

  // LEGS
  { id:'squat_bb', name:'Back Squat', category:'Legs', equipment:'Barbell', muscle:'Quadriceps', secondary:['Glutes','Hamstrings','Core'], instructions:'Bar on upper traps. Feet shoulder width. Squat until thighs parallel or below. Drive back up through heels.', tips:'Keep chest up and knees tracking over toes. Breathe in on way down.', sets:3, reps:8, emoji:'🏋️' },
  { id:'romanian_dl', name:'Romanian Deadlift', category:'Legs', equipment:'Barbell', muscle:'Hamstrings', secondary:['Glutes','Lower Back'], instructions:'Hold bar at hips. Hinge forward pushing hips back. Feel hamstring stretch. Drive hips forward to return.', tips:'Soft knee bend. Bar stays close to legs throughout. Feel the hamstring stretch.', sets:3, reps:10, emoji:'🏋️' },
  { id:'leg_press', name:'Leg Press', category:'Legs', equipment:'Machine', muscle:'Quadriceps', secondary:['Glutes','Hamstrings'], instructions:'Place feet shoulder width on platform. Lower weight until 90 degrees. Press back to near lockout.', tips:'Do not lock knees at top. Foot position changes muscle emphasis.', sets:3, reps:12, emoji:'🏋️' },
  { id:'lunges', name:'Lunges', category:'Legs', equipment:'Dumbbell', muscle:'Quadriceps', secondary:['Glutes','Hamstrings'], instructions:'Step forward with one leg. Lower until rear knee near floor. Push back to start or walk forward.', tips:'Keep front shin vertical. Upright torso for quad emphasis.', sets:3, reps:12, emoji:'🏋️' },
  { id:'leg_curl', name:'Leg Curl', category:'Legs', equipment:'Machine', muscle:'Hamstrings', secondary:[], instructions:'Lie face down on machine. Curl lower legs toward glutes. Squeeze at top. Lower with control.', tips:'Keep hips pressed into pad. Full range of motion.', sets:3, reps:12, emoji:'🏋️' },
  { id:'calf_raise', name:'Calf Raise', category:'Legs', equipment:'Machine', muscle:'Gastrocnemius', secondary:['Soleus'], instructions:'Stand on edge of platform with heels hanging. Rise up on toes as high as possible. Lower for full stretch.', tips:'Full stretch at bottom is key for calf development. Pause at top.', sets:4, reps:15, emoji:'🏋️' },

  // CORE
  { id:'plank', name:'Plank', category:'Core', equipment:'Bodyweight', muscle:'Transverse Abdominis', secondary:['Obliques','Erector Spinae'], instructions:'Forearms on floor, body in straight line. Hold position without letting hips drop or rise.', tips:'Squeeze glutes and abs simultaneously. Breathe steadily.', sets:3, reps:60, emoji:'💪' },
  { id:'crunch', name:'Crunch', category:'Core', equipment:'Bodyweight', muscle:'Rectus Abdominis', secondary:[], instructions:'Lie on back, knees bent. Lift shoulders off floor by contracting abs. Lower with control.', tips:'Do not pull neck. Focus on curling the spine, not sitting up.', sets:3, reps:20, emoji:'💪' },
  { id:'leg_raise', name:'Hanging Leg Raise', category:'Core', equipment:'Bodyweight', muscle:'Lower Rectus Abdominis', secondary:['Hip Flexors'], instructions:'Hang from bar. Raise legs to parallel or higher by flexing abs. Lower with control.', tips:'Do not swing. Posterior pelvic tilt to engage lower abs.', sets:3, reps:12, emoji:'💪' },
  { id:'russian_twist', name:'Russian Twist', category:'Core', equipment:'Bodyweight', muscle:'Obliques', secondary:['Rectus Abdominis'], instructions:'Sit with knees bent, lean back 45 degrees. Rotate torso side to side. Add weight for progression.', tips:'Keep feet off ground for more challenge. Rotate from torso not arms.', sets:3, reps:20, emoji:'💪' },

  // CARDIO
  { id:'running', name:'Running', category:'Cardio', equipment:'None', muscle:'Full Body', secondary:[], instructions:'Maintain steady pace. Land midfoot. Keep shoulders relaxed and arms at 90 degrees.', tips:'Breathe rhythmically. Start slow and build pace gradually.', sets:1, reps:30, emoji:'🏃' },
  { id:'cycling', name:'Cycling', category:'Cardio', equipment:'Machine', muscle:'Quadriceps', secondary:['Hamstrings','Glutes','Calves'], instructions:'Adjust seat height so slight knee bend at bottom of pedal stroke. Maintain steady cadence.', tips:'Higher resistance builds strength. Higher cadence improves endurance.', sets:1, reps:30, emoji:'🚴' },
  { id:'jump_rope', name:'Jump Rope', category:'Cardio', equipment:'None', muscle:'Calves', secondary:['Shoulders','Core'], instructions:'Hold handles at hip height. Jump with both feet. Keep elbows close to body. Small efficient jumps.', tips:'Land on balls of feet. Great warm up and cardio option.', sets:3, reps:60, emoji:'🏃' },
]

export const CATEGORIES = ['All','Chest','Back','Shoulders','Arms','Legs','Core','Cardio']

export const BODY_MUSCLES = {
  chest: { label:'Chest', muscles:['Pectoralis Major','Pectoralis Minor'], exercises: EXERCISES.filter(e=>e.category==='Chest') },
  back:  { label:'Back',  muscles:['Latissimus Dorsi','Trapezius','Rhomboids','Erector Spinae'], exercises: EXERCISES.filter(e=>e.category==='Back') },
  shoulders: { label:'Shoulders', muscles:['Anterior Deltoid','Lateral Deltoid','Posterior Deltoid'], exercises: EXERCISES.filter(e=>e.category==='Shoulders') },
  arms:  { label:'Arms',  muscles:['Biceps Brachii','Brachialis','Triceps Brachii'], exercises: EXERCISES.filter(e=>e.category==='Arms') },
  legs:  { label:'Legs',  muscles:['Quadriceps','Hamstrings','Glutes','Calves'], exercises: EXERCISES.filter(e=>e.category==='Legs') },
  core:  { label:'Core',  muscles:['Rectus Abdominis','Obliques','Transverse Abdominis'], exercises: EXERCISES.filter(e=>e.category==='Core') },
}
